name: kangaroo-build

on: push

jobs:
  setup-gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.1.3
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Execute Gradle Build
        run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs
    
